# peer_service

client_service와 함께 분산 처리를 완결한다. 

관계가 많이 생긴다. 
- 로컬 액터와 리모트 액터의 up / down 사용 인터페이스
- 피어의 down 시 리모트 액터 down 처리 

## use case 

리모트 액터를 쉽게 사용하도록 하는 것이 핵심 기능이다. 
리모트 액터가 로컬로 옮겨오더라도 동일한 코드로 동작해야 한다. 
이것이 관건이다. 

## 단계적 구현 

- 구성 파일 읽기 
- listen 
- connect
- 핸들러 등록 
- 핸들러 구현 
- 필요한 데이터 추가 
- syn_peer_up / syn_peer_down 메세지 추가 


## connect / accept / reconnect / disconnect

- reconnect 

## peer

연결을 피어로 만든다. 프로토콜만 기억한다. 

accept 받은 쪽에서 syn_peer_up을 보낸다. 이에 대한 답으로 syn_peer_up을 보낸다. 
accepted 에서 오는 syn_peer_up은 응답을 보내지 않는다. 

up까지 받으면 준비된 것이다. 

## 단선 처리 

단선 처리를 잘 되려면 액터들 up / down과 사용 구조가 있어야 한다. 
액터 up / down과 리모트 / 클라이언트 액터 사용을 고민해 본다. 

어떻게 찾아서 사용할 지, 어떻게 알 지가 중요하고 또 끊어지거나 내려가면 알 수 있어야 한다. 

## 디버깅 1 

중간 중간 단단하게 하면서 앞으로 간다. 

### 메인 쓰레드 스케줄링 

test_peer_service의 기본 실행에서 main 쓰레드가 매우 오래 지속되는 문제가 있다. 코드 구조로 보면 
1초 이내에 종료해야 하는데 그렇지 않다. 

지금은 현상이 잘 나오지 않고 있다. 왜 그럴 수 있는 지 생각하면서 진행한다. 

### actor_directory 종료 

~server 부터 소멸자 처리에서 예외가 발생했다. tcp_protocol 내부. 
람다의 캡처는 매우 미묘한 문제들을 만들 수 있다. this 참조와 같은 것, 
프로토콜 복사 등은 여러 가지 디버깅이 어려운 복잡한 문제를 만들 수 있다. 

테스트를 제거하고 하나씩 추가하면서 찾은 건 `test_bits_protocol.cpp`에서 부터 문제가 발생한다는 사실이다. 

여기서 시작한다. 

catch의 SECTION()을 if ( false )로 변경하면 disable 시킬 수 있다. 
에코 테스트에서 문제가 발생했다. 다행이 서버와 피어 서비스 쪽은 괜찮다. 

exit 중 fast fail로 들어가는 이상한 현상이다. 
함수들이 인라인 되어 디버깅하기가 어렵다. 

디버깅을 하면 동작이 달라진다. 이는 대부분 여러 쓰레드의 `실행 순서 변경`이 원인인 경우가 많다. 

crt terminate handler에서 완료를 하지 못 하면 abort()를 호출한다.

모호했던 부분들, 이해하지 못 한 것들은 항상 다시 올라온다. 명확해야 한다. 
tcp_node에서 마지막 정리하는 부분, disconnect면 에러 통지 되는 부분이 명확하지 않다. 

```
Release> .\wise.kernel.test.exe

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
wise.kernel.test.exe is a Catch v2.11.1 host application.
Run with -? for options

-------------------------------------------------------------------------------
bits protocol
  echo performance
-------------------------------------------------------------------------------
C:\wisemountain\wise.kernel\test\net\test_bits_protocol.cpp(404)
...............................................................................

C:\wisemountain\wise.kernel\test\net\test_bits_protocol.cpp(404): FAILED:
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal

===============================================================================
test cases:     20 |     19 passed | 1 failed
assertions: 100141 | 100140 passed | 1 failed

Release> .\wise.kernel.test.exe
===============================================================================
All tests passed (100300 assertions in 31 test cases)

Release> .\wise.kernel.test.exe
Release> .\wise.kernel.test.exe
Release> .\wise.kernel.test.exe
Release> .\wise.kernel.test.exe
```

몇 가지 힌트가 있다. 우선 echo performance에 메모리 관련 타이밍 오류가 있다는 것. 
비정상 종료할 때가 더 많다는 것. 

tcp_node에 이전에 구현했던 내용이 완벽했다. 
거의 처음으로 돌아왔지만 처음과 같지는 않다. 

object_pool.hpp의 153 라인에서 예외가 발생했다. 이 때문에 생긴 문제로 보인다. 
전에 본 적이 있는데 지나갔고 그래서 문제가 되었다.


**이제 알았다!!!**

- object_pool이 static으로 정의된 곳들이 꽤 있다. 
- 어떤 이유로 해제되지 않은 오브젝트가 있다. 
- 마지막 종료 시 예외가 발생하면 abort()를 타게 된다. 
- spdlog로 남기려던 것도 이미 spdlog 인스턴스 소멸 후라서 예외가 나왔다. 

어떻게 정리해야 할까? TLS로 넣은 것들 때문일까? 

object_pool의 150 라인이고 여기서 나온 오류이기 때문에 명확하다.
현재는 segment_buffer외에는 사용하는 곳이 없다. 
따라서, 해당 이슈만 추적해 가면 된다. 

exception에 로그를 추가하는 건 안 좋았던 생각이다. 
exception은 거의 언어 차원의 statement라고 봐야 한다. 

그래도 발생한다. 여기가 아닌가? 

```c++
>	wise.kernel.test.exe!abort() 줄 77	C++
 	wise.kernel.test.exe!terminate() 줄 58	C++
 	[외부 코드]	
 	wise.kernel.test.exe!_execute_onexit_table::__l2::<람다>() 줄 206	C++
 	wise.kernel.test.exe!__crt_seh_guarded_call<int>::operator()<<lambda_7777bce6b2f8c936911f934f8298dc43>,int <람다>(void) &,<lambda_3883c3dff614d5e0c5f61bb1ac94921c>>(__acrt_lock_and_call::__l2::<lambda_7777bce6b2f8c936911f934f8298dc43> && setup, _execute_onexit_table::__l2::int <람다>(void) & action, __acrt_lock_and_call::__l2::<lambda_3883c3dff614d5e0c5f61bb1ac94921c> && cleanup) 줄 204	C++
 	[인라인 프레임] wise.kernel.test.exe!__acrt_lock_and_call(const __acrt_lock_id) 줄 971	C++
 	wise.kernel.test.exe!_execute_onexit_table(_onexit_table_t * table) 줄 231	C++
 	wise.kernel.test.exe!common_exit::__l2::<람다>() 줄 232	C++
 	wise.kernel.test.exe!__crt_seh_guarded_call<void>::operator()<<lambda_d80eeec6fff315bfe5c115232f3240e3>,void <람다>(void) &,<lambda_2358e3775559c9db80273638284d5e45>>(__acrt_lock_and_call::__l2::<lambda_d80eeec6fff315bfe5c115232f3240e3> && setup, common_exit::__l2::void <람다>(void) & action, __acrt_lock_and_call::__l2::<lambda_2358e3775559c9db80273638284d5e45> && cleanup) 줄 224	C++
 	[인라인 프레임] wise.kernel.test.exe!__acrt_lock_and_call(const __acrt_lock_id) 줄 971	C++
 	wise.kernel.test.exe!common_exit(const int return_code, const _crt_exit_cleanup_mode cleanup_mode, const _crt_exit_return_mode return_mode) 줄 278	C++
```

이 정도 남기고 앞으로 나아간다. 








